<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My PHP Page</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            margin: 0;
            padding: 20px;
            color: #333;
        }
        header {
            background: #0078d7;
            color: white;
            padding: 20px;
            margin-bottom: 20px;
        }
        .container {
            max-width: 1200px;
            margin: 0 auto;
        }
    </style>
</head>
<body>
    <header>
        <div class="container">
            <h1>Welcome to MY Website</h1>
        </div>
    </header>

    <main class="container">
        <?php
        // PHP code starts here
        date_default_timezone_set('UTC');
        $current_time = date('Y-m-d H:i:s');
        $visitor_ip = $_SERVER['REMOTE_ADDR'];
        ?>

        <section>
            <h2>Server Information</h2>
            <p>Current server time: <?php echo $current_time; ?></p>
            <p>Your IP address: <?php echo $visitor_ip; ?></p>
            <p>PHP version: <?php echo phpversion(); ?></p>
        </section>

        <section>
            <h2>Dynamic Content</h2>
            <?php
            $greetings = ["Hello", "Welcome", "Greetings", "Hi there"];
            $random_greeting = $greetings[array_rand($greetings)];
            echo "<p>$random_greeting, visitor! This page was generated by PHP.</p>";
            ?>
        </section>
    </main>

    <footer class="container">
        <hr>
        <p>&copy; <?php echo date('Y'); ?> My Website. All rights reserved.</p>
    </footer>
</body>
</html>